### ISSUE TITLE
CommoditiesLevelTrader_cBot: uprava rizeni stop lossu dle reakce trhu

### ISSUE THREAD

**Issue by GeorgeQuantAnalyst** [GeorgeQuantAnalyst/cTraderBots#12]
Prosim o upravu utahovani stop lossu dle reakce trhu.

**Aktualni stav**
```
Trailing stop o velikosti entry - stop loss.
```

**Novy stav**
```
2. 1. Trh reaguje 50% do profitu -> utahnout stop loss na 80%
3. Trh reaguje 70% do profitu -> utahnout stop loss na vstup cenu
```

Upravu vytvorit ve vetvi: feature/manage_stop_loss_by_reaction.

Poznamka: Upravit taky aktivitni diagram.

**Comment by LucyQuantAnalyst** [comment]
Navrh uprav proveden ve vetvi [](https://github.com/GeorgeQuantAnalyst/cTraderBots/pull/14)
