### ISSUE TITLE
CommoditiesLevelTrader_cBot: chyba validace max objemu obchodu

### ISSUE THREAD

**Issue by GeorgeQuantAnalyst** [GeorgeQuantAnalyst/cTraderBots#18]
Prosim o upravu validace max povoleneho objemu obchodu, aby zohlednila taky to ze se pouziva paka, takze uzivatel muze mit na uctu 10x nebo i 20x mene nez je celkovy objem pozice.

**Aktualni kod**
```C#
if (amountInAccountCurrency > Account.Balance)
{
  errMessages.Add(String.Format("WARNING: Trade volume in account currency is greater that account balance: [AmountInAccountCurrency: {0}, AccountBalance: {1}]", amountInAccountCurrency, Account.Balance));
}
```

**Ocekvany kod**
```C#
if (amountInAccountCurrency / Symbol.Leverage > Account.Balance)
{
  errMessages.Add(String.Format("WARNING: Trade volume in account currency is greater that account balance: [AmountInAccountCurrency: {0}, AccountBalance: {1}]", amountInAccountCurrency, Account.Balance));
}
```

Dokumentace: https://help.ctrader.com/ctrader-automate/references/MarketData/Symbols/LeverageTier/?h=leverage#examples

**Comment by LucyQuantAnalyst** [comment]
Opraveno v commitu: [dfb20c34056b6e62c87e0704dbd4c7914ad3c144](https://github.com/GeorgeQuantAnalyst/cTraderBots/commit/dfb20c34056b6e62c87e0704dbd4c7914ad3c144)
