### ISSUE TITLE
CommoditiesLevelTrader_cBot: zruseni vypnuti bota kdyz se SL posune na BE

### ISSUE THREAD

**Issue by GeorgeQuantAnalyst** [GeorgeQuantAnalyst/cTraderBots#20]
Prosim o zruseni vypinani bota, kdyz se posune SL na BE. Bot se vypina pri uzavreni pozice, kdy se nasledne do logu zapise i vysledek obchodu (zisk/ztrata).

**Comment by LucyQuantAnalyst** [comment]
Opraveno v commitu: [0e3fdf1a073ba3bb1d1158679bec71f229da34de](https://github.com/GeorgeQuantAnalyst/cTraderBots/commit/0e3fdf1a073ba3bb1d1158679bec71f229da34de)
