### ISSUE TITLE
CommoditiesLevelTrader_cBot: nefunkcni trailovani SL na trhu XAGUSD long

### ISSUE THREAD

**Issue by GeorgeQuantAnalyst** [GeorgeQuantAnalyst/cTraderBots#22]
Prosim o provereni proc se netrailoval SL po dosazeni trailingStopLossLevel1 a trailingStopLossLevel2 urovne, kdyz cena prokazatelne dosla na tyto urovne.

DealID: DID24318952
Obchod: xauusd, long, 20230927

**Graf**
![Image](https://github.com/GeorgeQuantAnalyst/cTraderBots/assets/112611533/fbb289b7-b94c-426c-8134-735991ad0626)

**Log**

[xagusd.log](https://github.com/GeorgeQuantAnalyst/cTraderBots/files/12762052/xagusd.log)

**Comment by GeorgeQuantAnalyst** [comment]
# Analyza

Dle logu to vypada, ze nezafungoval listener, ktery je nastaveny ze pri otevreni pozice zaloguje informaci o vstupni cene a nastavi promennou isActivePosition na true. Pak logicky uz nefungoval ani trailing stop, protoze kontrola trailing levelu probiha pouze pokud je promenna isActivePosition nastavena na true.

Zatim se jedna o ojedinely pripad, napriklad na SOYOIL probehlo zaregistrovani otevreni pozice v poradku.

Bug budeme dale monitorovat a v pripade opakovani se zamerime proc nezafungoval listener.

**Comment by LucyQuantAnalyst** [comment]
# Reseni:

Pridani overeni pro kazdou minutu jestli je oterena pozice a neni nastaveno IsActivePosition na TRUE tak ho na TRUE nastav

```C#
if (!IsActivePosition){
                foreach (Position pos in Positions)
                {
                    if (TradeId.SequenceEqual(pos.Comment)){
                        Print("Pending order was converted to position.");
                        Print("Position opened at {0}", pos.EntryPrice);
                        IsActivePosition = true;
                    }
                 }
            }

```

Opraveno v commitu: [5889fb1cef3da25d1db6a1d9be8dec476f1ce2e3](https://github.com/GeorgeQuantAnalyst/cTraderBots/commit/5889fb1cef3da25d1db6a1d9be8dec476f1ce2e3)
